---
- name: Dependencies to build CONMON
  become: yes
  apt:
    name: ['gcc', 'git', 'libc6-dev', 'libglib2.0-dev','pkg-config', 'make', 'runc', 'golang-go']

- name: CONMON repository pulled
  become: yes
  git:
    repo: https://github.com/containers/conmon
    dest: /srv/conmon
    version: v2.0.26

- name: CONMON built
  become: yes
  community.general.make:
    chdir: /srv/conmon
    target: install