- name: Modules are well loaded for CRI-O
  become: true
  copy:
    src: crio.conf
    dest: /etc/modules-load.d/crio.conf

- name: overlay is well-configured for CRI-O
  become: true
  community.general.modprobe:
    name: overlay
    state: present

- name: CRI-O is well configured for Kubernetes in sysctl
  become: true
  copy:
    src: 99-kubernetes-cri.conf
    dest: /etc/sysctl.d/99-kubernetes-cri.conf
  notify: Reload sysctl

- name: The repository for libcontainer for Ubuntu is installed
  become: true
  template:
    src: crio-repository/ubuntu/devel-kubic-libcontainers-stable-OS.list
    dest: /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
  when: ansible_distribution == "Ubuntu"

- name: The repository for CRI-O for Ubuntu is installed
  become: true
  template:
    src: crio-repository/ubuntu/devel-kubic-libcontainers-stable-OS-VERSION.list
    dest: "/etc/apt/sources.list.d/devel:kubic:libcontainers:stable:cri-o:{{ CRIO_VERSION }}.list"
  when: ansible_distribution == "Ubuntu"

- name: GPG key is added for libcontainers
  become: true
  apt_key:
    url: "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{ CRIO_REPOSITORY_DISTRIBUTION_VERSION }}/Release.key"
    keyring: /etc/apt/trusted.gpg.d/libcontainers.gpg
    state: present
  when: ansible_distribution == "Ubuntu"

- name: GPG key is added for CRI-O 
  become: true
  apt_key:
    url: "https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:{{ CRIO_VERSION }}/{{ CRIO_REPOSITORY_DISTRIBUTION_VERSION }}/Release.key"
    keyring: /etc/apt/trusted.gpg.d/libcontainers-cri-o.gpg
    state: present
  when: ansible_distribution == "Ubuntu"

- name: CRI-O installed on Ubuntu
  become: true
  apt:
    update_cache: yes
    name: ['cri-o', 'cri-o-runc']
    state: present
  when: ansible_distribution == "Ubuntu" or ansible_distribution  == "Debian"
  notify: Enable CRI-O svc

- name: cgroup driver is configured
  become: true
  copy:
    src: 02-cgroup-manager.conf
    dest: /etc/crio/crio.conf.d/02-cgroup-manager.conf

- name: CRIO started
  become: yes
  systemd:
    name: crio
    state: started
