- name: Configure modules for Cri-o
  become: true
  copy:
    src: crio.conf
    dest: /etc/modules-load.d/crio.conf

- name: overlay is well-configured for cri-o
  become: true
  community.general.modprobe:
    name: overlay
    state: present

- name: Configure cri-o for Kubernetes in sysctl
  become: true
  copy:
    src: 99-kubernetes-cri.conf
    dest: /etc/sysctl.d/99-kubernetes-cri.conf