---
# tasks file for prepare-k8s-node
- name: br_netfilter is well-configured
  become: true
  community.general.modprobe:
    name: br_netfilter
    state: present
  notify: Reload sysctl

- name: Bridge configuration is setup for k8s
  become: true
  copy:
    src: k8s.conf
    dest: /etc/sysctl.d/k8s.conf

- name: Install conmon on ubuntu
  include_tasks: install-conmon.yaml

- name: Install cri-o on ubuntu
  include_tasks: install-cri-o.yaml

- name: Install Kubernetes components
  include_tasks: install-kube-components.yaml