---
# handlers file for prepare-k8s-node
- name: Reload sysctl
  become: true
  ansible.posix.sysctl:
    reload: yes

- name: Enable CRI-O svc
  become: true
  systemd:
    name: crio
    enabled: yes
    daemon_reload: yes